[package]
name = "gemsrv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.19.1"
webpki-roots = "0.21.0"
url = "2.2.2"